/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in as admin
         * @description Exchange an admin username + password for a bearer JWT.
         *
         *     Returns `data.access_token` (send it as `Authorization: Bearer <token>`) and `data.expires_at`.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard overview
         * @description Aggregated home view for a shift day: tonight's attendance, the weekly lateness
         *     summary, the count of missing reports, at-risk goals, and stale project topics.
         */
        get: operations["dashboard_overview_api_v1_dashboard_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tonight's attendance
         * @description The attendance record for each person on the given shift day, ordered by roster.
         */
        get: operations["get_today_attendance_api_v1_attendance_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Attendance history grid
         * @description A rows=people × cols=days grid over `[from, to]`. Days with no record return a
         *     `missing` cell, so every person has a full, gap-free row.
         */
        get: operations["get_attendance_history_api_v1_attendance_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/weekly-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Weekly attendance summary
         * @description Per-person counts of each attendance status (on_time / late / late_15 / no_show /
         *     absent) for the Mon–Sun week beginning at `week_start`. `meta` echoes the resolved
         *     `week_start`/`week_end`.
         */
        get: operations["get_weekly_summary_api_v1_attendance_weekly_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/{record_id}/chase-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update chase state
         * @description Set the chase state (`none` / `needs_chase` / `chased` / `resolved`) on one
         *     attendance record and return the updated record.
         */
        patch: operations["patch_chase_state_api_v1_attendance__record_id__chase_state_patch"];
        trace?: never;
    };
    "/api/v1/reports/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily reports
         * @description Each person's report for the given day — summary, extras, rating (1–4), missing
         *     flag, source topic, and their active assignments.
         */
        get: operations["get_daily_reports_api_v1_reports_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Performance leaderboard
         * @description Per-person performance over `[from, to]`, best→worst: WHAT (avg rating + trend, completion %,
         *     accomplishment) + HOW (avg check-in/out, status counts, compensation, avg hours, punctuality) +
         *     the output-anchored **composite grade** (attendance penalises; latest feedback adjusts ±1 band).
         *     Completion % is over Mon–Sat work-days.
         */
        get: operations["get_performance_api_v1_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viper/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upsert weekly evaluation (Viper)
         * @description Idempotent upsert of a person's holistic WHAT/HOW/WHY evaluation for a period (keyed on
         *     person + period_start + period_end). Produced weekly by Viper's performance-evaluation skill.
         */
        post: operations["viper_evaluation_api_v1_viper_evaluation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evaluations in a window
         * @description Evaluations whose period overlaps `[from, to]`, newest period first (latest per person is the
         *     one the Performance tab shows under WHY).
         */
        get: operations["get_evaluations_api_v1_evaluations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viper/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add feedback note (Viper)
         * @description Append a feedback note for a person (Abdul's judgment, logged as spoken). `grade_adjustment`
         *     (-1/0/+1) lets the most recent feedback in a window nudge the composite grade by a band.
         */
        post: operations["viper_feedback_api_v1_viper_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Feedback in a window
         * @description Feedback notes dated within `[from, to]`, newest first — the per-person timeline under WHY.
         */
        get: operations["get_feedback_api_v1_feedback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List goals
         * @description All goals (status derived from deadline), each with owner, progress, deadline,
         *     next nudge, and the latest progress-log entry. Optionally filter by `status`.
         */
        get: operations["get_goals_api_v1_goals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/project-conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Project conditions
         * @description Condition for each project topic — rolling summary, last activity, the open task
         *     checklist, and the recent log timeline. Active projects only by default; pass
         *     `include_archived=true` to also return archived ones (so they can be restored).
         */
        get: operations["get_project_conditions_api_v1_project_conditions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a project
         * @description Create a new project topic and its condition. `topic_id` is auto-generated when omitted.
         */
        post: operations["create_project_endpoint_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a project
         * @description Permanently remove a project, its condition, and its logs. Referencing goals are detached.
         */
        delete: operations["delete_project_endpoint_api_v1_projects__topic_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update a project
         * @description Patch a project's title, summary, task checklist, or active (archive) flag. Omitted
         *     fields are left unchanged; archive sets `active=false` (hides it from the board).
         */
        patch: operations["update_project_endpoint_api_v1_projects__topic_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{topic_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a project log entry
         * @description Append a timestamped log entry and bump the project's last activity. Returns the full project.
         */
        post: operations["add_project_log_endpoint_api_v1_projects__topic_id__logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{topic_id}/logs/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a project log entry
         * @description Remove a single log entry from a project. Returns the full project.
         */
        delete: operations["delete_project_log_endpoint_api_v1_projects__topic_id__logs__log_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viper/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upsert attendance (Viper)
         * @description Idempotent upsert of one person's attendance for a shift day (keyed on person + date).
         *     The person is created on first sight. The attendance status is derived server-side.
         */
        post: operations["viper_attendance_api_v1_viper_attendance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viper/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upsert daily report (Viper)
         * @description Idempotent upsert of one person's daily report (keyed on person + date). Returns the report id.
         */
        post: operations["viper_report_api_v1_viper_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viper/goal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upsert goal (Viper)
         * @description Idempotent upsert of a goal (keyed on `slug`). `progress_log`, if present, is appended
         *     as a timestamped log entry. Returns the resolved goal.
         */
        post: operations["viper_goal_api_v1_viper_goal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/viper/project-condition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upsert project condition (Viper)
         * @description Idempotent upsert of a topic's rolling condition (keyed on `topic_id`) — summary,
         *     last activity, and open items. Returns the resolved condition.
         */
        post: operations["viper_project_condition_api_v1_viper_project_condition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sheets/sync/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync attendance to the sheet
         * @description Push current attendance to the configured HR sheet and return the sync run's status.
         */
        post: operations["sheets_sync_attendance_api_v1_sheets_sync_attendance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/google-sheet/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview the HR sheet
         * @description Spreadsheet title and, per tab, its dimensions, sample range, and a few sample rows —
         *     used to verify the Google Sheet wiring before importing.
         */
        get: operations["google_sheet_preview_api_v1_google_sheet_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/google-sheet/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import recognized tabs
         * @description Import rows from tabs with recognizable canonical headers into the dashboard, returning
         *     counts of imported rows and any skipped tabs.
         */
        post: operations["google_sheet_import_api_v1_google_sheet_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/import-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import attendance from the HR sheet now
         * @description Pull the wide `Sigma Attendnace` tab into the dashboard immediately — the same job the
         *     daily 19:00 Asia/Tashkent auto-sync runs. Returns the recorded sync run (status + summary).
         */
        post: operations["import_attendance_sheet_now_api_v1_attendance_import_sheet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttendanceCell */
        AttendanceCell: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Status */
            status: ("on_time" | "late" | "late_15" | "no_show" | "absent") | "missing";
            /** Check In At */
            check_in_at?: string | null;
            /** Check Out At */
            check_out_at?: string | null;
        };
        /** AttendanceHistoryRow */
        AttendanceHistoryRow: {
            person: components["schemas"]["PersonOut"];
            /** Cells */
            cells: components["schemas"]["AttendanceCell"][];
        };
        /** AttendanceOut */
        AttendanceOut: {
            /** Id */
            id: number;
            person: components["schemas"]["PersonOut"];
            /**
             * Shift Date
             * Format: date
             */
            shift_date: string;
            /** Check In At */
            check_in_at: string | null;
            /** Check Out At */
            check_out_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "on_time" | "late" | "late_15" | "no_show" | "absent";
            /** Minutes Late */
            minutes_late: number;
            /**
             * Chase State
             * @enum {string}
             */
            chase_state: "none" | "needs_chase" | "chased" | "resolved";
            /** Notes */
            notes: string | null;
        };
        /** ChasePatchRequest */
        ChasePatchRequest: {
            /**
             * Chase State
             * @example chased
             * @enum {string}
             */
            chase_state: "none" | "needs_chase" | "chased" | "resolved";
        };
        /** DashboardOverview */
        DashboardOverview: {
            /** Today Attendance */
            today_attendance: components["schemas"]["AttendanceOut"][];
            /** Weekly Summary */
            weekly_summary: components["schemas"]["WeeklySummaryRow"][];
            /** Missing Reports Count */
            missing_reports_count: number;
            /** At Risk Goals */
            at_risk_goals: components["schemas"]["GoalOut"][];
            /** Stale Project Topics */
            stale_project_topics: components["schemas"]["ProjectConditionOut"][];
        };
        /**
         * Envelope
         * @description Standard response envelope used by every endpoint.
         *
         *     On success, `data` holds the typed payload and `error` is `null`. On failure,
         *     `data` is `null` and `error` carries a machine-readable `code` plus a `message`.
         *     `meta` carries optional pagination/context (e.g. `week_start`, `week_end`).
         */
        Envelope: {
            /** Data */
            data?: unknown | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[AttendanceOut] */
        Envelope_AttendanceOut_: {
            data?: components["schemas"]["AttendanceOut"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[DashboardOverview] */
        Envelope_DashboardOverview_: {
            data?: components["schemas"]["DashboardOverview"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[EvaluationOut] */
        Envelope_EvaluationOut_: {
            data?: components["schemas"]["EvaluationOut"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[FeedbackOut] */
        Envelope_FeedbackOut_: {
            data?: components["schemas"]["FeedbackOut"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[GoalOut] */
        Envelope_GoalOut_: {
            data?: components["schemas"]["GoalOut"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[GoogleSheetImportResult] */
        Envelope_GoogleSheetImportResult_: {
            data?: components["schemas"]["GoogleSheetImportResult"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[GoogleSheetPreview] */
        Envelope_GoogleSheetPreview_: {
            data?: components["schemas"]["GoogleSheetPreview"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[IdResult] */
        Envelope_IdResult_: {
            data?: components["schemas"]["IdResult"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[LoginResponse] */
        Envelope_LoginResponse_: {
            data?: components["schemas"]["LoginResponse"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[ProjectConditionOut] */
        Envelope_ProjectConditionOut_: {
            data?: components["schemas"]["ProjectConditionOut"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[ProjectDeleted] */
        Envelope_ProjectDeleted_: {
            data?: components["schemas"]["ProjectDeleted"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[SheetSyncResult] */
        Envelope_SheetSyncResult_: {
            data?: components["schemas"]["SheetSyncResult"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[list[AttendanceHistoryRow]] */
        Envelope_list_AttendanceHistoryRow__: {
            /** Data */
            data?: components["schemas"]["AttendanceHistoryRow"][] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[list[AttendanceOut]] */
        Envelope_list_AttendanceOut__: {
            /** Data */
            data?: components["schemas"]["AttendanceOut"][] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[list[EvaluationOut]] */
        Envelope_list_EvaluationOut__: {
            /** Data */
            data?: components["schemas"]["EvaluationOut"][] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[list[FeedbackOut]] */
        Envelope_list_FeedbackOut__: {
            /** Data */
            data?: components["schemas"]["FeedbackOut"][] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[list[GoalOut]] */
        Envelope_list_GoalOut__: {
            /** Data */
            data?: components["schemas"]["GoalOut"][] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[list[PerformanceRow]] */
        Envelope_list_PerformanceRow__: {
            /** Data */
            data?: components["schemas"]["PerformanceRow"][] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[list[ProjectConditionOut]] */
        Envelope_list_ProjectConditionOut__: {
            /** Data */
            data?: components["schemas"]["ProjectConditionOut"][] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[list[ReportOut]] */
        Envelope_list_ReportOut__: {
            /** Data */
            data?: components["schemas"]["ReportOut"][] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** Envelope[list[WeeklySummaryRow]] */
        Envelope_list_WeeklySummaryRow__: {
            /** Data */
            data?: components["schemas"]["WeeklySummaryRow"][] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorBody"] | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** EvaluationOut */
        EvaluationOut: {
            /** Id */
            id: number;
            person: components["schemas"]["PersonOut"];
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Grade */
            grade: string;
            /** What */
            what: string;
            /** How */
            how: string;
            /** Why */
            why: string;
            /** Composite Score */
            composite_score: number | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** FeedbackOut */
        FeedbackOut: {
            /** Id */
            id: number;
            person: components["schemas"]["PersonOut"];
            /**
             * Feedback Date
             * Format: date
             */
            feedback_date: string;
            /** Note */
            note: string;
            /** Source */
            source: string | null;
            /** Grade Adjustment */
            grade_adjustment: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** GoalOut */
        GoalOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            owner: components["schemas"]["PersonOut"] | null;
            /** Topic Id */
            topic_id: string | null;
            /** Deadline */
            deadline: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "overdue" | "done" | "paused";
            /** Progress Percent */
            progress_percent: number;
            /** Last Update At */
            last_update_at: string | null;
            /** Next Nudge At */
            next_nudge_at: string | null;
            /** Latest Log */
            latest_log: string | null;
        };
        /** GoogleSheetImportResult */
        GoogleSheetImportResult: {
            /** Spreadsheet Id */
            spreadsheet_id: string;
            /** Spreadsheet Title */
            spreadsheet_title: string;
            /** Imported */
            imported: {
                [key: string]: number;
            };
            /** Skipped Tabs */
            skipped_tabs: string[];
            /** Notes */
            notes: string[];
        };
        /** GoogleSheetPreview */
        GoogleSheetPreview: {
            /** Spreadsheet Id */
            spreadsheet_id: string;
            /** Spreadsheet Title */
            spreadsheet_title: string;
            /** Configured Name */
            configured_name: string;
            /** Tabs */
            tabs: components["schemas"]["GoogleSheetTabPreview"][];
        };
        /** GoogleSheetTabPreview */
        GoogleSheetTabPreview: {
            /** Title */
            title: string;
            /** Row Count */
            row_count: number;
            /** Column Count */
            column_count: number;
            /** Sample Range */
            sample_range: string;
            /** Values */
            values: string[][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdResult
         * @description Minimal acknowledgement returned by write endpoints that only confirm an id.
         */
        IdResult: {
            /** Id */
            id: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Username
             * @example admin
             */
            username: string;
            /**
             * Password
             * @example your-admin-password
             */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** PerformanceRow */
        PerformanceRow: {
            person: components["schemas"]["PersonOut"];
            /** Average Rating */
            average_rating: number | null;
            /** Report Completion Rate */
            report_completion_rate: number;
            /** Missing Days */
            missing_days: number;
            /** Assignment Count */
            assignment_count: number;
            /** Top Accomplishment */
            top_accomplishment?: string | null;
            /** Rating Trend */
            rating_trend?: components["schemas"]["RatingPoint"][];
            /** Avg Check In */
            avg_check_in?: string | null;
            /** Avg Check Out */
            avg_check_out?: string | null;
            /**
             * On Time Count
             * @default 0
             */
            on_time_count: number;
            /**
             * Late Count
             * @default 0
             */
            late_count: number;
            /**
             * Late15 Count
             * @default 0
             */
            late15_count: number;
            /**
             * No Show Count
             * @default 0
             */
            no_show_count: number;
            /**
             * Absent Count
             * @default 0
             */
            absent_count: number;
            /**
             * Attendance Days
             * @default 0
             */
            attendance_days: number;
            /**
             * Punctuality Rate
             * @default 0
             */
            punctuality_rate: number;
            /**
             * Compensates
             * @default false
             */
            compensates: boolean;
            /** Avg Hours */
            avg_hours?: number | null;
            /**
             * Composite Grade
             * @default Under
             */
            composite_grade: string;
            /**
             * Composite Score
             * @default 0
             */
            composite_score: number;
        };
        /** PersonOut */
        PersonOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Display Name */
            display_name: string;
            /** Active */
            active: boolean;
            /** Sort Order */
            sort_order: number;
        };
        /** ProjectConditionOut */
        ProjectConditionOut: {
            /** Topic Id */
            topic_id: string;
            /** Title */
            title: string | null;
            /** Summary */
            summary: string | null;
            /** Last Activity At */
            last_activity_at: string | null;
            /** Open Items */
            open_items: components["schemas"]["ProjectTask"][];
            /** Logs */
            logs?: components["schemas"]["ProjectLogOut"][];
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * ProjectCreate
         * @description Admin: create a new project. `topic_id` is auto-generated when omitted.
         */
        ProjectCreate: {
            /** Title */
            title: string;
            /** Topic Id */
            topic_id?: string | null;
            /** Summary */
            summary?: string | null;
            /** Open Items */
            open_items?: components["schemas"]["ProjectTask"][];
        };
        /** ProjectDeleted */
        ProjectDeleted: {
            /** Topic Id */
            topic_id: string;
        };
        /** ProjectLogCreate */
        ProjectLogCreate: {
            /** Body */
            body: string;
        };
        /** ProjectLogOut */
        ProjectLogOut: {
            /** Id */
            id: number;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ProjectTask
         * @description A single checklist item for a project. `done` toggles completion.
         */
        ProjectTask: {
            /** Text */
            text: string;
            /**
             * Done
             * @default false
             */
            done: boolean;
        };
        /**
         * ProjectUpdate
         * @description Admin: patch a project. Every field is optional; omitted fields are left unchanged.
         */
        ProjectUpdate: {
            /** Title */
            title?: string | null;
            /** Summary */
            summary?: string | null;
            /** Open Items */
            open_items?: components["schemas"]["ProjectTask"][] | null;
            /** Active */
            active?: boolean | null;
        };
        /** RatingPoint */
        RatingPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Rating */
            rating: number;
        };
        /** ReportOut */
        ReportOut: {
            /** Id */
            id: number;
            person: components["schemas"]["PersonOut"];
            /**
             * Report Date
             * Format: date
             */
            report_date: string;
            /** Summary */
            summary: string;
            /** Extras */
            extras: string | null;
            /** Rating */
            rating: number | null;
            /** Missing */
            missing: boolean;
            /** Source Topic */
            source_topic: string | null;
            /** Assignments */
            assignments?: string[];
        };
        /**
         * SheetSyncResult
         * @description Outcome of a Google Sheet attendance sync run.
         */
        SheetSyncResult: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Error Message */
            error_message?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ViperAttendanceUpsert */
        ViperAttendanceUpsert: {
            person: components["schemas"]["ViperPersonRef"];
            /**
             * Shift Date
             * Format: date
             * @example 2026-06-03
             */
            shift_date: string;
            /**
             * Check In At
             * @example 2026-06-03T18:02:00+05:00
             */
            check_in_at?: string | null;
            /** Check Out At */
            check_out_at?: string | null;
            /**
             * Status
             * @example late_15
             */
            status?: ("on_time" | "late" | "late_15" | "no_show" | "absent") | null;
            /**
             * Chase State
             * @default none
             * @enum {string}
             */
            chase_state: "none" | "needs_chase" | "chased" | "resolved";
            /** Notes */
            notes?: string | null;
        };
        /** ViperEvaluationUpsert */
        ViperEvaluationUpsert: {
            person: components["schemas"]["ViperPersonRef"];
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Grade */
            grade: string;
            /**
             * What
             * @default
             */
            what: string;
            /**
             * How
             * @default
             */
            how: string;
            /**
             * Why
             * @default
             */
            why: string;
            /** Composite Score */
            composite_score?: number | null;
        };
        /** ViperFeedbackUpsert */
        ViperFeedbackUpsert: {
            person: components["schemas"]["ViperPersonRef"];
            /**
             * Feedback Date
             * Format: date
             */
            feedback_date: string;
            /** Note */
            note: string;
            /** Source */
            source?: string | null;
            /**
             * Grade Adjustment
             * @default 0
             */
            grade_adjustment: number;
        };
        /** ViperGoalUpsert */
        ViperGoalUpsert: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Owner Slug */
            owner_slug?: string | null;
            /** Topic Id */
            topic_id?: string | null;
            /** Deadline */
            deadline?: string | null;
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "overdue" | "done" | "paused";
            /**
             * Progress Percent
             * @default 0
             */
            progress_percent: number;
            /** Last Update At */
            last_update_at?: string | null;
            /** Next Nudge At */
            next_nudge_at?: string | null;
            /** Progress Log */
            progress_log?: string | null;
        };
        /** ViperPersonRef */
        ViperPersonRef: {
            /** Slug */
            slug: string;
            /** Display Name */
            display_name: string;
        };
        /** ViperProjectConditionUpsert */
        ViperProjectConditionUpsert: {
            /** Topic Id */
            topic_id: string;
            /** Summary */
            summary: string;
            /** Last Activity At */
            last_activity_at?: string | null;
            /** Open Items */
            open_items?: string[];
        };
        /** ViperReportUpsert */
        ViperReportUpsert: {
            person: components["schemas"]["ViperPersonRef"];
            /**
             * Report Date
             * Format: date
             */
            report_date: string;
            /** Summary */
            summary: string;
            /** Extras */
            extras?: string | null;
            /** Rating */
            rating?: number | null;
            /**
             * Missing
             * @default false
             */
            missing: boolean;
            /** Source Topic */
            source_topic?: string | null;
        };
        /** WeeklySummaryRow */
        WeeklySummaryRow: {
            person: components["schemas"]["PersonOut"];
            /** On Time */
            on_time: number;
            /** Late */
            late: number;
            /** Late 15 */
            late_15: number;
            /** No Show */
            no_show: number;
            /** Absent */
            absent: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_LoginResponse_"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_overview_api_v1_dashboard_overview_get: {
        parameters: {
            query?: {
                /** @description Shift day (YYYY-MM-DD); defaults to today. */
                shift_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DashboardOverview_"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_today_attendance_api_v1_attendance_today_get: {
        parameters: {
            query?: {
                /** @description Shift day (YYYY-MM-DD); defaults to today. */
                shift_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_AttendanceOut__"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attendance_history_api_v1_attendance_history_get: {
        parameters: {
            query: {
                /** @description Inclusive start day (YYYY-MM-DD). */
                from: string;
                /** @description Inclusive end day (YYYY-MM-DD). */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_AttendanceHistoryRow__"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Invalid query parameters (e.g. `to` before `from`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    get_weekly_summary_api_v1_attendance_weekly_summary_get: {
        parameters: {
            query: {
                /** @description Monday of the target week (YYYY-MM-DD). */
                week_start: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_WeeklySummaryRow__"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_chase_state_api_v1_attendance__record_id__chase_state_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChasePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AttendanceOut_"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_reports_api_v1_reports_daily_get: {
        parameters: {
            query: {
                /** @description Report day (YYYY-MM-DD). */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_ReportOut__"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_performance_api_v1_performance_get: {
        parameters: {
            query: {
                /** @description Inclusive start day (YYYY-MM-DD). */
                from: string;
                /** @description Inclusive end day (YYYY-MM-DD). */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_PerformanceRow__"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    viper_evaluation_api_v1_viper_evaluation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViperEvaluationUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_EvaluationOut_"];
                };
            };
            /** @description Missing or invalid `X-Viper-Token`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluations_api_v1_evaluations_get: {
        parameters: {
            query: {
                /** @description Inclusive start day (YYYY-MM-DD). */
                from: string;
                /** @description Inclusive end day (YYYY-MM-DD). */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_EvaluationOut__"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    viper_feedback_api_v1_viper_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViperFeedbackUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_FeedbackOut_"];
                };
            };
            /** @description Missing or invalid `X-Viper-Token`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feedback_api_v1_feedback_get: {
        parameters: {
            query: {
                /** @description Inclusive start day (YYYY-MM-DD). */
                from: string;
                /** @description Inclusive end day (YYYY-MM-DD). */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_FeedbackOut__"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_goals_api_v1_goals_get: {
        parameters: {
            query?: {
                /** @description Optional filter: active | overdue | done | paused. */
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_GoalOut__"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_conditions_api_v1_project_conditions_get: {
        parameters: {
            query?: {
                /** @description Include archived (active=false) projects. */
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_ProjectConditionOut__"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_endpoint_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProjectConditionOut_"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description A project with that topic_id already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_endpoint_api_v1_projects__topic_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProjectDeleted_"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_endpoint_api_v1_projects__topic_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProjectConditionOut_"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_project_log_endpoint_api_v1_projects__topic_id__logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProjectConditionOut_"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_log_endpoint_api_v1_projects__topic_id__logs__log_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
                log_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProjectConditionOut_"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    viper_attendance_api_v1_viper_attendance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViperAttendanceUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AttendanceOut_"];
                };
            };
            /** @description Missing or invalid `X-Viper-Token`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    viper_report_api_v1_viper_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViperReportUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_IdResult_"];
                };
            };
            /** @description Missing or invalid `X-Viper-Token`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    viper_goal_api_v1_viper_goal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViperGoalUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_GoalOut_"];
                };
            };
            /** @description Missing or invalid `X-Viper-Token`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    viper_project_condition_api_v1_viper_project_condition_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViperProjectConditionUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProjectConditionOut_"];
                };
            };
            /** @description Missing or invalid `X-Viper-Token`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sheets_sync_attendance_api_v1_sheets_sync_attendance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SheetSyncResult_"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    google_sheet_preview_api_v1_google_sheet_preview_get: {
        parameters: {
            query?: {
                /** @description Rows to sample per tab (1–25). */
                sample_rows?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_GoogleSheetPreview_"];
                };
            };
            /** @description Google Sheet could not be read or imported. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_sheet_import_api_v1_google_sheet_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_GoogleSheetImportResult_"];
                };
            };
            /** @description Google Sheet could not be read or imported. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    import_attendance_sheet_now_api_v1_attendance_import_sheet_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SheetSyncResult_"];
                };
            };
            /** @description Missing or invalid admin bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
}
